name: build
on:
  pull_request:
  push:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: |
            build/libs/criteria_sync-*.jar
            !build/libs/criteria_sync-*-sources.jar

      - name: upload release assets
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v7
        with:
          name: ReleaseAssets
          path: |
            build/libs/criteria_sync-*.jar
            !build/libs/criteria_sync-*-sources.jar

  publish:
    name: Upload to release
    needs: [build]
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v5
        with:
          name: ReleaseAssets
          path: release_assets

      - name: upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ./release_assets/*
